### ISSUE TITLE
Table Component

### ISSUE THREAD

**Issue by logan-laughery** [logan-laughery/field-guide-ui#16]
Create a new table component:
![2020-10-03-103334_758x548_scrot](https://user-images.githubusercontent.com/23034303/94995464-13ae7180-0564-11eb-9d25-b385ca602f67.png)
(the example above illustrates a list within a card component)

The component should accept the following properties:
- `items` - array of objects in any shape to be shown in the table.
- `headers` - array of objects defining the columns found in the table.  Each of these objects should have the following properties:
  - `label` - string used for the title of the column
  - `valueKey` - string that represents a key found in an `items` object to be used for retrieving the values to show in the column
  - `rightAlign` - bool that causes the column to be right aligned if true

The documentation should also be updated to describe the use of this new component.

**Comment by kamerat** [comment]
I'll hack together a PR once I'm off work.
I like this project idea 💯

**Comment by logan-laughery** [comment]
Resolved with #23
