### ISSUE TITLE
Improve Table Component API

### ISSUE THREAD

**Issue by logan-laughery** [logan-laughery/field-guide-ui#25]
Explore api options discussed in feedback on #23
> I believe the API could be improved a bit in order to make the component props more customizable. By adding a reduce prop, the user could choose what function should be run to display the items for example instead of forcing the user to use the pattern 'label', 'valueKey', 'rightAlign' on the headers

@kamerat Are you able to provide a quick example of what passing these new properties to the table component would look like?

**Comment by kamerat** [comment]
I have hacked on some different ideas, but as stated in #24 

> I personally have the most experience using the Vuetify component library and would look to their style and api when determining how components in this library should behave.

I root for keeping this with minor changes like;
 * Rename `valueKey` to `value`
 * Rename `rightAlign` to `align` & change behavior accordingly

**Comment by logan-laughery** [comment]
Closed in #28
