### ISSUE TITLE
Framework prefix

### ISSUE THREAD

**Issue by kamerat** [logan-laughery/field-guide-ui#27]
I believe it is a good idea to create a prefix for the components as seen in the [style guide](https://vuejs.org/v2/style-guide/#Base-component-names-strongly-recommended).

`<Card>` would then be `<FCard>`/`<FGCard>`/`<FG-Card>`... you name it!  _(literally)_

**Comment by logan-laughery** [comment]
@kamerat Good suggestion!  Personally, I lean towards the `<fg-card>` style, using a dash similar to [how vuetify does things](https://vuetifyjs.com/en/components/cards/).

All three options sound good to me though!

**Comment by kamerat** [comment]
I too like the `fg-x` prefix, looks better lowercase as you typed it.
Should we go for `fg-kebab-case` as vuetify does, `fg-camelCase` or `fg-PascalCase`?

**Comment by logan-laughery** [comment]
I vote we go with `fg-kebab-case`

**Comment by kamerat** [comment]
🥙-case it is 💯
