### ISSUE TITLE
Prefix components

### ISSUE THREAD

**Issue by kamerat** [logan-laughery/field-guide-ui#30]
Currently, all the components are not prefixed. We could like to add the prefix `fg` to all components.
This includes the component name, filename, import name and element name as seen in the table below.

- [ ] All lib components should be renamed to the following convention: `fgComponentName`

### Example:

| Type           | Current                                         | Wanted                                                |
|----------------|-------------------------------------------------|-------------------------------------------------------|
| Filename       | `ImageContainer.vue `                              | `FgImageContainer.vue`                                 |
| import name    |` import ImageContainerfrom './ImageContainer.vue'` | `import FgImageContainer from './FgImageContainer.vue'` |
| Component name | `name: 'ImageContainer' `                          | `name: 'FgImageContainer' `                            |
| Component element| `<image-container></image-container>`                          | `<fg-image-container></fg-image-container> `                            |

**Comment by kamerat** [comment]
Do you prefer the CSS class-names also be prefixed @logan-laughery ?

**Comment by logan-laughery** [comment]
@kamerat Prefixing the css names sounds good to me.

I'm curious if we want to change the casing on the file names themselves though.  I believe the [style guide is recommending this approach:](https://vuejs.org/v2/style-guide/#Component-name-casing-in-JS-JSX-strongly-recommended)


| Type           | Current                                         | Wanted                                                |
|----------------|-------------------------------------------------|-------------------------------------------------------|
| Filename       | `ImageContainer.vue `                              | `FgImageContainer.vue`                                 |
| import name    |` import ImageContainerfrom './ImageContainer.vue'` | `import FgImageContainer from './FgImageContainer.vue'` |
| Component name | `name: 'ImageContainer' `                          | `name: 'FgImageContainer' `                            |
| Component element| `<image-container></image-container>`                          | `<fg-image-container></fg-image-container> `                            |

**Comment by kamerat** [comment]
> I'm curious if we want to change the casing on the file names themselves though. 

I must have misunderstood you earlier then 😄  

Pascal for components it is 💯 

I'll update the issue accordingly. Can you add the `hacktoberfest` tag to this task in additional to `good first issue` maybe?

**Comment by zashton** [comment]
@kamerat @logan-laughery  would like to contribute , do assign me this issue 👍

**Comment by kamerat** [comment]
Feel free to take it @zashton, glad to hear you want to help! I believe @logan-laughery has no issues with it 😃

**Comment by zashton** [comment]
> Feel free to take it @zashton, glad to hear you want to help! I believe @logan-laughery has no issues with it 😃

awesome, have just sent PR. 😄
