### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by kamerat** [logan-laughery/field-guide-ui#33]
First off, I don't know how much motivation and time you have for this project @logan-laughery and if I am too exited for this VS what I should be (since this is a random public repo) 😅 Therefore, it would be nice to hear from you what your thoughts and milestones around this project are.

I totally understand if you did not intend for this to be this _"serious"_ and require more time than you were willing to put in it. This might totally not be the case, but I just don't want to stress you out with PR's and make you feel you **have** to put time in this. This issue will help me and future people get some insight in what you have in mind. You did briefly describe the origins of the repo in the other issue, but I find it better not to hijack that issue with that.

I would therefore love to hear where you want to go with this repo, as I really love the idea in its wholeness and your design looks PERFECT for the vision. This is what makes me this exited to be able to contribute to this idea.

If you do have motivation and time for this to be something more, then I would love to continue discussing in this issue milestones here on out. I can start the ball with saying it would be smart to establish a npm package so that it is possible _read; easier_ to use the framework - I think this is a must have for this to start growing and get used.

Looking forward to hear from you, @logan-laughery.

**Comment by logan-laughery** [comment]
@kamerat Time is definitely the enemy!  If others are contributing to this project, I'll definitely be motivated to dedicate more time to it.  I'm really happy to see someone express this level of enthusiasm in the project and I'm certainly not stressed out with the number of PR's or issues being generated.

I believe I'll have enough time to treat this as a serious project.  However, this will be the first vue component library that I've attempted to maintain and I'd hate to hinder its ability to grow.  Because of this, I welcome any and all suggestions for helping this library be successful.

I agree that putting together a list of concrete milestones will be beneficial for all who contribute to the library.  Starting with getting an npm package published sounds like a great place to start.  From there, we likely need to come to some agreement on what a comprehensive list of components for a library such as this looks like and add those to the list of milestones.

**Comment by kamerat** [comment]
Sounds good man. I'm glad to hear so!

> From there, we likely need to come to some agreement on what a comprehensive list of components for a library such as this looks like and add those to the list of milestones.

I agree, getting it out first is a great start. I have no experience with NPM releasing myself, but I think you should at least create an account if you haven't already and register the name before someone else does. After that, we can make a dedicated issue regarding publishing to npm and maybe get some help.

**Comment by logan-laughery** [comment]
I got the name locked down: https://www.npmjs.com/package/field-guide-ui  I'll get a milestone created for npm set up and start adding issues to it.

Do you think we should add milestones for individual components? This is the list of components/design system elements I'm thinking need to be included:

#### Design System Boilerplate
- Color
- Typography

#### Form Components
- Input (Text, Numeric, etc)
- Text Area
- Radio
- Checkbox
- Select (Dropdowns)
- Date
- Button

#### Other Components
- Alert
- Loading Indicator
- Menu
- Sidebar

I'm sure there are plenty of additional elements that will be needed so let me know what else should be added.

I'm leaning towards making milestones for each component and breaking the work down into multiple issues (likely one issue for the design phase, one for the initial implementation of the component, and additional issues if the component has a few style variations that end users can apply).

Also, how do you feel about automated tests?  Do we need unit tests or end-to-end tests?

**Comment by kamerat** [comment]
Awesome!

> Do you think we should add milestones for individual components?

I think it would be nice, makes it easier to track progress and roadmap 💯 

> I'm sure there are plenty of additional elements that will be needed so let me know what else should be added.

I think this list is very well for now, if someone has any input, they can just create an issue/PR regarding it 😄 

> Also, how do you feel about automated tests? 

I like tests and I think it is a good idea! However, myself, I have little to no experience in writing tests.. 😓 But I'm glad to learn.

I think this wraps this issue down in regards to my goals of it. 
Let's move this to issues and link them to milestones ⏭️ 

This will be awesome, thank you! 💯
